ALTER TABLE "ProduitVariante"
ALTER COLUMN "quantiteStock" TYPE DOUBLE PRECISION
USING "quantiteStock"::DOUBLE PRECISION;

ALTER TABLE "ProduitVariante"
ALTER COLUMN "quantiteStock" SET DEFAULT 0;

ALTER TABLE "Stock"
ALTER COLUMN "quantite" TYPE DOUBLE PRECISION
USING "quantite"::DOUBLE PRECISION;

ALTER TABLE "Stock"
ALTER COLUMN "quantite" SET DEFAULT 0;

ALTER TABLE "StockMovement"
ALTER COLUMN "quantite" TYPE DOUBLE PRECISION
USING "quantite"::DOUBLE PRECISION;

ALTER TABLE "VenteLigne"
ALTER COLUMN "quantite" TYPE DOUBLE PRECISION
USING "quantite"::DOUBLE PRECISION;

ALTER TABLE "Retour"
ALTER COLUMN "quantite" TYPE DOUBLE PRECISION
USING "quantite"::DOUBLE PRECISION;
