export const ROUTE_PATHS = {
  LOGIN: "/",
  DASHBOARD: "/dashboard",
  POS: "/pos",
  PRODUCTS: "/products",
  STOCK: "/stock",
  COMPTES: "/comptes",
  SUPPLIERS: "/suppliers",
  SALES: "/sales",
  REPORTS: "/reports",
  USERS: "/users",
  ORGANISATIONS: "/organisations",
  STORES: "/stores",
  CUSTOMERS: "/customers",
  PURCHASES: "/purchases",
  EXPENSES: "/expenses",
  AVOIRS: "/avoirs",
};
